### ISSUE TITLE
[component] progress bar

### ISSUE THREAD

**Issue by moebiusmania** [bitrockteam/amber-components#23]
A classical horizontal progress bar, very similar to the current `<amber-progress>` component. 
Developed as a separated component to not overload the current one.

### Proposed syntax
```html
<amber-progress-bar
  label="my progress bar"
  stroke="2" 
  value="50"
></amber-progress-bar>
```

### Details
- **label:** text to display
- **stroke:** same as `<amber-progress>`
- **value:** always a %

It **could** dispatch an  `updated` event when the value change.

Main color can be defined from outside via CSS variable and/or HTML attribute.

**Comment by moebiusmania** [comment]
quite needed in a current project (Kafka GeoStream)

**Comment by alessandromenini** [comment]
Since we are going to create a new horizontal progress bar, could we maybe split the current circular progress into a new Spinner component?

We could have two components:

### 1. Spinner (loading state)

### 2. Progress bar (when we need to show the progress of something)
- **mode:** circular or horizontal
